# Generated by Django 2.2.2 on 2019-06-28 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hotel',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=150, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tourist',
            name='food',
            field=models.ManyToManyField(to='tourists.Food', verbose_name='Питание'),
        ),
    ]
